on: [push]

env:
  ProjectName: LGML
  PackagesVersion: 1.2.9
jobs:
  osx:
    name: OSX
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Checkout JUCE
        uses: actions/checkout@v2
        with:
          repository: benkuper/JUCE
          ref: develop-local
          path: JUCE

      - name : Path check
          run: |
              pwd
              ls
              curl -L -o Packages.dmg 'http://s.sudre.free.fr/Software/files/Packages.dmg'
              hdiutil mount Packages.dmg
              sudo installer -pkg /Volumes/Packages\ ${{ PackagesVersion }}/Install\ Packages.pkg -target /
              hdiutil detach /Volumes/Packages\ ${{ PackagesVersion }}/
      - name: Build
        uses: sersoft-gmbh/xcodebuild-action@v1.3
        with:
          project: Builds/MacOSX_CI/${{ env.ProjectName }}.xcodeproj
          destination: platform=macOS
          jobs: 2
          action: build
          use-xcpretty: false

