on: [push]

env:
  ProjectName: LGML
  PackagesVersion: 1.2.9

jobs:
  osx:
    name: OSX
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Download Packages 
        run: |
          curl -L -o Packages.dmg 'http://s.sudre.free.fr/Software/files/Packages.dmg'
          hdiutil mount Packages.dmg
          sudo installer -pkg /Volumes/Packages/ ${{ env.PackagesVersion }}/Install/ Packages.pkg -target /
          hdiutil detach /Volumes/Packages/ ${{ env.PackagesVersion }}/
          
      - name: Checkout JUCE
        uses: actions/checkout@v2
        with:
          repository: benkuper/JUCE
          ref: develop-local
          path: JUCE

      - name: Build
        uses: sersoft-gmbh/xcodebuild-action@v1.3
        with:
          project: Builds/MacOSX_CI/${{ env.ProjectName }}.xcodeproj
          destination: platform=macOS
          jobs: 2
          action: build
          use-xcpretty: true

      - uses: FranzDiebold/github-env-vars-action@v1.2.1
      - name: Set Suffix
        id: set_suffix
        run: |
          echo "GITHUB_REF_NAME=${{ env.GITHUB_REF_NAME }}"
          if [$GITHUB_REF_NAME == 'master']
          then
              echo "::set-output name=suffix::bleedingedge"
          else
              echo "::set-output name=suffix::${{ GITHUB_REF_NAME }}"
          fi

      - name: Create Package
        run:  |
          cd Packages
          packagesbuild ${{ ProjectName }}.pkgproj \
          mv ${{ ProjectName }}.pkg ${{ ProjectName }}-osx-${{ steps.set_suffix.outputs.suffix }}.pkg

      - name: Upload
        uses: wei/curl@v1
        with:
          args: -X POST https://httpbin.org/post

